
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE
IF
	EXISTS `refs`;
CREATE TABLE `refs` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL,
	`parent_id` BIGINT NOT NULL,	
	`created_at` BIGINT NULL DEFAULT NULL,
	`updated_at` BIGINT NULL DEFAULT NULL,
	PRIMARY KEY ( `id` ) USING BTREE,		
	INDEX `user_id` ( `user_id`) USING BTREE,
	INDEX `parent_id` ( `parent_id`) USING BTREE,
	CONSTRAINT `ref_user_id_FK` FOREIGN KEY ( `user_id` ) REFERENCES `users` ( `id` ) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT `ref_parent_id_FK` FOREIGN KEY ( `parent_id` ) REFERENCES `users` ( `id` ) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER 
SET = utf8mb4 COLLATE = utf8mb4_bin ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;