const OffsetBlockChain = {
    SCAN_BLOCK_OFFSET_ETH_TESTNET: 2995,
    SCAN_BLOCK_OFFSET_BSC_TESTNET: 2995,
    SCAN_BLOCK_OFFSET_POLYGON_TESTNET: 2995,

    SCAN_BLOCK_OFFSET_ETH_MAINNET: 1024,
    SCAN_BLOCK_OFFSET_BSC_MAINNET: 1024,
    SCAN_BLOCK_OFFSET_POLYGON_MAINNET: 2995,
};

module.exports = OffsetBlockChain;
