module.exports = {
    apps: [
        {
            name: "Super_Smash_Bros_Backend App",
            script: "/home/ubuntu/.nvm/versions/node/v16.18.1/bin/yarn",
            args: "app",
            instances: 1,
            exec_mode: "cluster",
            autorestart: true,
            max_memory_restart: "500M",
        },
        {
            name: "Super_Smash_Bros_Backend Socket",
            script: "/home/ubuntu/.nvm/versions/node/v16.18.1/bin/yarn",
            args: "socket",
            instances: 1,
            exec_mode: "cluster",
            autorestart: true,
            max_memory_restart: "500M",
        },
        {
            name: "Super_Smash_Bros_Backend Cron",
            script: "/home/ubuntu/.nvm/versions/node/v16.18.1/bin/yarn",
            args: "cron",
            instances: 1,
            exec_mode: "cluster",
            autorestart: true,
            max_memory_restart: "500M",
        },
        {
            name: "Super_Smash_Bros_Backend Queue",
            script: "/home/ubuntu/.nvm/versions/node/v16.18.1/bin/yarn",
            args: "queue",
            instances: 1,
            exec_mode: "cluster",
            autorestart: true,
            max_memory_restart: "1G",
        },
        {
            name: "Super_Smash_Bros_Backend ETH",
            script: "/home/ubuntu/.nvm/versions/node/v16.18.1/bin/yarn",
            args: "eth",
            instances: 1,
            exec_mode: "cluster",
            autorestart: true,
            max_memory_restart: "300M",
        },
    ],
};
