module.exports = {
  corePlugins: {
    preflight: false,
  },
  darkMode: 'class', // or 'media' or 'class'
  mode: "jit",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./common/**/*.{js,ts,jsx,tsx}",
    "./modules/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        primary: {
          light: "var(--color-primary-light)",
          DEFAULT: "var(--color-primary)",
          dark: "var(--color-primary-dark)",
        },
        accent: {
          light: "var(--color-accent-light)",
          DEFAULT: "var(--color-accent)",
          dark: "var(--color-accent-dark)",
        },
        bgCoreTeam: "#F8F8F8",
        "white-spinel": "#FAFAFD",
        "primary-blue":"#A9DFFC"


      },
      fontFamily: {
        // body: ['Open Sans', 'sans-serif'],
        body: ["hk_grotesk", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        cabinet: ["Cabinet Grotesk", "sans-serif"],
      },
      fontSize: {
        8: "8px",
        10: "10px",
        12: "12px",
        14: "14px",
        16: "16px",
        18: "18px",
        20: "20px",
        24: "24px",
        30: "30px",
        48: "48px",
        72: "72px",

      },
      lineHeight: {
        14: "14px",
        20: "20px",
        28: "28px",
        32: "32px",
        60: "60px",
        80: "80px",

      },
      borderWidth: {
        0.5: "0.5px",
      },
      maxWidth: {
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
        9: "2.25rem",
        10: "2.5rem",
        11: "2.75rem",
        12: "3rem",
        13: "3.25rem",
        14: "3.5rem",
        15: "3.75rem",
        16: "4rem",
        18: "4.5rem",
        20: "5rem",
        22: "5.5rem",
        24: "6rem",
        28: "7rem",
        "4xs": "8rem",
        "3xs": "12rem",
        "2xs": "16rem",
      },
      minWidth: {
        none: "none",
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
        9: "2.25rem",
        10: "2.5rem",
        11: "2.75rem",
        12: "3rem",
        13: "3.25rem",
        14: "3.5rem",
        15: "3.75rem",
        16: "4rem",
        18: "4.5rem",
        20: "5rem",
        22: "5.5rem",
        24: "6rem",
        28: "7rem",
        "4xs": "8rem",
        "3xs": "12rem",
        "2xs": "16rem",
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
        "screen-sm": "640px",
        "screen-md": "768px",
        "screen-lg": "1024px",
        "screen-xl": "1280px",
        "screen-2xl": "1536px",
      },
      height: {
        min: "min-content",
        max: "max-content",
        18: "4.5rem",
        22: "5.5rem",
        26: "26px",
        52: "52px",
        60: "60px",
      },

     width: {
      "108px": "108px",
      },
      minHeight: {
        none: "none",
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
        9: "2.25rem",
        10: "2.5rem",
        11: "2.75rem",
        12: "3rem",
        13: "3.25rem",
        14: "3.5rem",
        15: "3.75rem",
        16: "4rem",
        18: "4.5rem",
        20: "5rem",
        22: "5.5rem",
        24: "6rem",
        28: "7rem",
        "4xs": "8rem",
        "3xs": "12rem",
        "2xs": "16rem",
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
        min: "min-content",
      },
      borderRadius: {
        inherit: "inherit",
      },
      keyframes: {
        wiggle: {
          "100%": { transform: "rotate(-180deg)" },
          "0%": { transform: "rotate(180deg)" },
        },
        emerge: {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        fade: {
          from: { opacity: 1 },
          to: { opacity: 0 },
        },
        emergeUp: {
          from: { opacity: 0, transform: "translateY(4px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        slideInBottom: {
          from: { opacity: 0, transform: "translateY(100%)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        slideOutBottom: {
          from: { opacity: 1, transform: "translateY(0)" },
          to: { opacity: 0, transform: "translateY(100%)" },
        },
        slideInLeft: {
          from: { opacity: 0, transform: "translateX(-100%)" },
          to: { opacity: 1, transform: "translateX(0)" },
        },
        slideOutLeft: {
          from: { opacity: 1, transform: "translateX(0)" },
          to: { opacity: 0, transform: "translateX(-100%)" },
        },
        slideInRight: {
          from: { opacity: 0, transform: "translateX(100%)" },
          to: { opacity: 1, transform: "translateX(0)" },
        },
        slideOutRight: {
          from: { opacity: 1, transform: "translateX(0)" },
          to: { opacity: 0, transform: "translateX(100%)" },
        },
        scaleUp: {
          from: { opacity: 0, transform: "scale(0)" },
          to: { opacity: 1, transform: "scale(1)" },
        },
        scaleDown: {
          from: { opacity: 1, transform: "scale(1)" },
          to: { opacity: 0, transform: "scale(0)" },
        },
      },
      zIndex: {
        100: "100",
        200: "200",
        300: "300",
        400: "400",
        500: "500",
      },
      animation: {
        wiggle: "wiggle 10s linear infinite",
        emerge: "emerge 0.2s ease-in",
        fade: "fade .2s ease-out forwards",
        "emerge-up": "emergeUp .2s ease-in",
        "slide-in-bottom": "slideInBottom .2s ease-in",
        "slide-out-bottom": "slideOutBottom .2s ease-out forwards",
        "scale-up": "scaleUp .2s ease-in",
        "scale-down": "scaleDown .2s ease-out forwards",
        "slide-in-left": "slideInLeft .2s ease-in",
        "slide-out-left": "slideOutLeft .2s ease-out forwards",
        "slide-in-right": "slideInRight .2s ease-in",
        "slide-out-right": "slideOutRight .2s ease-out forwards",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        DEFAULT: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        "3xl": "0 35px 60px -15px rgba(0, 0, 0, 0.3)",
        inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
        none: "none",
        around: "0px 8px 48px rgba(0, 0, 0, 0.12)",
      },
      backgroundImage: {
        "header":"url('/images/header.png')",
        main: "url('/svg/bg-blank.svg')",
        "blue-conic":
          "conic-gradient(from 180deg at 50% 50%, #0088CC 0deg, #1751E7 108.75deg, #4A75E6 223.13deg, #3C9BE0 320.63deg, #0088CC 360deg)",
        "dark-conic":
          "conic-gradient(from 180deg at 50% 50%, #0D132E -39.37deg, #0D132E 22.5deg, #111C3A 108.75deg, #0F1736 223.13deg, #0D132E 320.63deg, #0D132E 382.5deg)",
        treasury: "url('/svg/bg-treasury.svg')",
        detail: "url('/images/Background Header include Grid.svg')",
        detailM: "url('/images/BG header Mobi.svg')",
        "dark-blue": "linear-gradient(99.02deg, #16224F -0.81%, #0F1C4B 107.65%)",
        clubItem: "url('/svg/card-item.svg')",
      },
      padding: {
        "1px": "1px",
        "25px": "25px",
        "30px": "30px",
        "120px": "120px",
        "200px": "200px"

      },
      margin: {
        200: "200px"
      },
    },
  },
  plugins: [require("@tailwindcss/aspect-ratio")],
  variants: {
    // ...
    scrollbar: ["dark"],
    pointerEvents: ["disabled"],
    cursor: ["disabled"],
    opacity: ["disabled"],
    fill: ["hover", "focus"],
    backgroundColor: ["checked"],
    borderColor: ["checked"],
    textColor: ["checked"],
    scale: ["active", "group-hover"],
    opacity: ["disabled"],
  },
};
